export interface IProduct {
  id:string,
  Color: string,
  CreatedAt?: string,
  Description:string,
  Images: string[],
  Length: number,
  Width:number,
  Name: string,
  ProductName: string,
  Price: number,
  Quantity: number,
  material: string,
  Online: boolean,
  SubCategory:string,
}
